"""
SeekableCTR — counter (CTR) mode over the 3-map chaos keystream. RESEARCH ARTIFACT.

THE PROBLEM IT SOLVES (random access):
  The streaming engines (engine.py / multimap.py) are a *tape*: to get keystream byte N you must
  generate bytes 0..N-1 first. You can't decrypt the middle of a 1 GB file without spooling the
  whole thing, and you can't parallelize.

THE FIX (CTR mode):
  Treat the keystream as a *phone book*. Cut it into fixed-size BLOCKs. The keystream for block i
  is derived *independently* from (master_key, nonce, block_index=i) via the same domain-separated
  SHA-512 KDF the multimap uses — with the block counter folded in. So:

      keystream[pos]  lives in  block = pos // BLOCK_SIZE,  at  offset = pos % BLOCK_SIZE

  To read any position you derive ONE block (O(BLOCK_SIZE) work) regardless of how far in it is.
  This is exactly the AES-CTR construction (keystream_block_i = PRF(key, nonce, i)), with the
  3-map chaos keystream playing the role of the PRF.

WHY THIS IS SOUND (and inherits the multimap's properties):
  * Each block = the proven 3-independent-PWLCM XOR keystream (see multimap.py), just re-seeded
    per block. The per-map invertibility is still hidden behind the XOR of three maps.
  * The block counter is domain-separated in the KDF, so distinct blocks are cryptographically
    unrelated — no structure links block i to block i+1 (unlike the streaming map, where they're
    one continuous orbit). This is strictly MORE separation than the streaming mode, not less.

THE HONEST COST:
  Every block pays a fresh KDF (3 SHA-512) + warmup, so CTR is somewhat slower per byte than the
  continuous stream (measured in bench/speed.py). The win is O(1) random access + parallelizability.

STILL UNVETTED. Seekability is a *capability*, not a security proof. See REPORT.md.
"""

from __future__ import annotations

import hashlib

from constants import DEFAULT_N_MAPS
from engine import DiscreteChaoticEngine


class SeekableCTR:
    """Seekable, counter-mode keystream over N independent PWLCM maps.

    Parameters
    ----------
    master_key : bytes
        The shared secret.
    nonce : bytes
        Public, unique per message. Folded into every block+map derivation.
    n_maps : int
        Independent maps XOR-combined per block (default 4 = the multi-body design).

    The keystream is identical no matter how you slice it: ``keystream(n, offset=k)`` always
    returns the same global bytes ``k .. k+n-1``. That is the whole point — random access.
    """

    # Keystream bytes per counter block. Bigger = less per-block KDF overhead, but a random
    # read wastes up to BLOCK_SIZE-1 generated bytes. 64 balances seek granularity vs overhead.
    BLOCK_SIZE = 64

    def __init__(self, master_key: bytes, nonce: bytes, n_maps: int = DEFAULT_N_MAPS):
        if n_maps < 1:
            raise ValueError("n_maps must be >= 1")
        self.master_key = master_key
        self.nonce = nonce
        self.n_maps = n_maps

    def _block_engine(self, block_index: int, map_index: int) -> DiscreteChaoticEngine:
        """Derive the independent sub-map for (block_index, map_index). BOTH counters are folded
        into the hash, so every (block, map) pair gets an unrelated (seed_key, control)."""
        h = hashlib.sha512(
            b"chaos-pwlcm-v1|ctr|"
            + block_index.to_bytes(8, "big")
            + b"|" + map_index.to_bytes(2, "big")
            + b"|" + self.master_key + b"|" + self.nonce
        ).digest()
        seed_key = int.from_bytes(h[0:24], "big")
        control = int.from_bytes(h[24:48], "big")
        return DiscreteChaoticEngine(seed_key, control, nonce=0)

    def _block_keystream(self, block_index: int) -> bytes:
        """The BLOCK_SIZE keystream bytes for one block = XOR of n_maps independent sub-maps."""
        engines = [self._block_engine(block_index, i) for i in range(self.n_maps)]
        out = bytearray(self.BLOCK_SIZE)
        for j in range(self.BLOCK_SIZE):
            b = 0
            for eng in engines:
                b ^= eng.generate_byte()
            out[j] = b
        return bytes(out)

    def keystream(self, n: int, offset: int = 0) -> bytes:
        """Return n keystream bytes starting at absolute byte ``offset`` — the seekable core.

        Only the blocks covering [offset, offset+n) are derived; earlier blocks are skipped
        entirely. That is the random-access win over the streaming engines."""
        if n < 0 or offset < 0:
            raise ValueError("n and offset must be non-negative")
        out = bytearray()
        pos = offset
        while len(out) < n:
            block_index, within = divmod(pos, self.BLOCK_SIZE)
            block = self._block_keystream(block_index)
            chunk = block[within:]
            out.extend(chunk)
            pos += len(chunk)
        return bytes(out[:n])

    def encrypt(self, data: bytes, offset: int = 0) -> bytes:
        """XOR ``data`` with the keystream starting at ``offset``. Seekable: decrypting a slice
        only needs that slice's offset, not the bytes before it."""
        ks = self.keystream(len(data), offset)
        return bytes(a ^ b for a, b in zip(data, ks))

    # XOR stream cipher: decrypt == encrypt (same offset)
    decrypt = encrypt


if __name__ == "__main__":
    key = b"my shared secret key"
    nonce = b"unique-nonce-001"

    c = SeekableCTR(key, nonce)

    # 1) determinism: two instances agree
    a = SeekableCTR(key, nonce).keystream(16)
    b = SeekableCTR(key, nonce).keystream(16)
    print(f"determinism: {a.hex()} == {b.hex()}  -> {a == b}")

    # 2) seekability: a window read mid-stream matches the same slice of the full keystream
    full = c.keystream(300)
    window = c.keystream(20, offset=137)          # jump straight to byte 137
    print(f"\nseek matches full stream: {window == full[137:157]}")
    print(f"  full[137:157] = {full[137:157].hex()}")
    print(f"  keystream(20, offset=137) = {window.hex()}")

    # 3) round-trip with an offset (e.g. decrypting just the tail of a file)
    msg = b"the middle of a large file, decrypted without reading the start."
    ct = c.encrypt(msg, offset=1000)
    pt = SeekableCTR(key, nonce).decrypt(ct, offset=1000)
    print(f"\noffset round-trip: {pt == msg}  ->  {pt!r}")

    # 4) random access really skips work: reading 1 byte at position 1e6 derives just 1 block
    far = c.keystream(1, offset=1_000_000)
    print(f"\nbyte @ position 1,000,000 (one block derived, not a million): {far.hex()}")
